# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 19:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldkcs',
            name='detail',
            field=models.CharField(blank=True, db_column='Detail', max_length=200),
        ),
        migrations.AlterField(
            model_name='oldkcs',
            name='receive_date',
            field=models.DateTimeField(db_column='ReceiveDate', default=datetime.datetime(2017, 5, 9, 19, 5, 22, 687000, tzinfo=utc)),
        ),
    ]
