# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eim', '0002_auto_20170509_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldkcs',
            name='receive_date',
            field=models.DateField(auto_now=True, db_column='ReceiveDate'),
        ),
    ]
