# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eim', '0003_auto_20170510_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('old_kcs_number', models.CharField(blank=True, db_column='OldKcs', max_length=30)),
                ('serial_number', models.CharField(db_column='SerialNumber', max_length=30, unique=True)),
                ('type', models.CharField(choices=[('SVRV5', 'Server V.5'), ('SVRV6', 'Server V.5'), ('JBOD', 'JBOD'), ('SWICH', 'Switch')], db_column='Type', max_length=3)),
                ('new_kcs_number', models.CharField(blank=True, db_column='NewKcsNumber', max_length=30)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Received', 'Received'), ('Testing', 'Testing'), ('Finished', 'Finished'), ('Packed', 'Packed'), ('Billed', 'Billed')], db_column='Status', default='Created', max_length=10)),
                ('memo', models.CharField(blank=True, db_column='Memo', max_length=2000)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='oldkcs',
            name='kcs_number',
            field=models.CharField(db_column='OldKcsNumber', default='Error Input', max_length=20, unique=True),
        ),
    ]
